### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Untittledmiss** [apankowski/doc88-downloader#22]
**Bug description - actual behavior**

When clicking the bookmark the download does not start and the file moves to the first page but not contunue. it remains static.

**Expected behavior**

It should start downloading the pages as gpg.

**Reproduction steps**

Steps to reproduce the issue:

1. Go to 'https://github.com/apankowski/doc88-downloader/blob/master/bookmark.min.js'
2. Create a browser bookmark, pasting content of the code in the page (exactly as it is) in its URL field.
3. Go to 'https://www.doc88.com/p-57587087487951.html'
4. Click on the browser bookmark created. 

**Environment**

* Tool version: https://github.com/apankowski/doc88-downloader/blob/master/bookmark.min.js
* Browser version: Microsoft Edge / Microsoft Bing (latest)
* OS version: Windows 11, 
* Link to doc88 document: https://www.doc88.com/p-62529340615848.html
* Output in Developer Console (if applicable) NA
* Installed browser extensions that add/modify/remove webpages (e.g. AdBlock, 1password, etc.) NA

**Additional context**

Any additional context related to the issue:

* Does the issue happen always on sometimes? Always
    * If sometimes, when does the issue happen? 
* Have you tried other system / device / internet connection? CHROME
    * If so, what were the results? The issue is the same, it seems it does not work anymore.
* Screenshots
* etc.

**Comment by apankowski** [comment]
@Untittledmiss issues #19, #21 and #22 all seem to be related to captcha that doc88 introduced.

I've added handling of captcha in #23 and merged.

You'll still have to solve the captcha, but after solving it the download process should progress.

Please try again with the new bookmark / code that's in the repo's default branch and report if it's working.
